### ISSUE TITLE
Nothing is saved to the local model

### ISSUE THREAD

**Issue by fjfish** [kalasjocke/authlogic-facebook-connect#1]
Hi Joakim -

I added this to the session.rb file (line 75)

```
        Facebooker::User::STANDARD_FIELDS.each do |f|
          if new_user.respond_to?(f)
            new_user[f] = facebook_session.user.send(f)
          end
        end
```

If the user model has fields with the same names, e.g. first_name it will populate the record when it creates it.

**Comment by kalasjocke** [comment]
And what happens? The new record dos'nt get the data from the facebooker gem or what?

**Comment by fjfish** [comment]
It wasn't populating any fields but the bare minimum to make it work as a facebook login, so I put the change in to at least store their name locally if there were any matching fields. I had a method called display name in my app that wasn't showing anything.

Hope this is enough, it may not be what's needed.

**Comment by thillerson** [comment]
The only problem is that by Facebook's terms of service, your app isn't allowed to store anything but numeric IDs. There's probably a way to make the facebook_session populate a list of fields from Facebook automatically each request. Does that sound like a good idea?

**Comment by kalasjocke** [comment]
Yeah, but there is a problem whit that to, that is that each request to facebook takes approx 1 sek slowing down the request to your app. I think that caching the information for some time giving a nice user experience is alright. I have some code in my trunk that will implement an after_connect hook leaving this to the user to implement.

What to you think of that?

**Comment by thillerson** [comment]
That's a great idea, Joakim

**Comment by kalasjocke** [comment]
Im sorry for this late push, but the before_connect hook is now in place! I use it like this in my app.

```
def before_connect(facebook_session)
  self.name = facebook_session.user.name
end
```
