### ISSUE TITLE
Any reasons why there isn't a "Registration" step? and/or saving facebook_uid?

### ISSUE THREAD

**Issue by bfolkens** [kalasjocke/authlogic-facebook-connect#10]
Patch - http://gist.github.com/256345

Behaves similarly to some other authlogic open-id-like login add-ons.  You can "register" the user with:

```
<%= hidden_field_tag 'register_with_facebook_connect', '' %>
<%= link_to_function 'Register with Facebook', "FB.Connect.requireSession(function() { $('register_with_facebook_connect').value = 'true'; $('user_form').submit(); }); return false;", :class => 'facebook_auth' %>
```

**Comment by milgner** [comment]
Tried it out, but somehow session_class.controller.facebook_session is nil in session_facebook_uid. Any ideas?

**Comment by bfolkens** [comment]
I _believe_ there's another post or ticket about that issue somewhere else...
