### ISSUE TITLE
SystemStackError (stack level too deep)

### ISSUE THREAD

**Issue by pftg** [kalasjocke/authlogic-facebook-connect#11]
At first, I don't know where you resolve in normal cases.  But I found this bug when I logged to site with facebook_connect and then recreate database. So I found exception. I dive deeper to your library and found that you have infinity callback calling in line:

validate :validate_by_facebook_connect, :if => :authenticating_with_facebook_connect?

and you call save in  validate_by_facebook_connect, so it recursivly call itself. I fix it by this code:

```
 def validate_by_facebook_connect
    facebook_session = controller.facebook_session
    self.attempted_record = facebook_user_class.find(:first, :conditions => { facebook_uid_field => facebook_session.user.uid })

    if self.attempted_record
      self.attempted_record.update_attribute(facebook_session_key_field, facebook_session.session_key)
    end
```

Please add fix in new version

**Comment by ghost** [comment]
Thanks! This solved an issue I had
