### ISSUE TITLE
 authlogic_facebook_connect plugin does not seem to logout fully

### ISSUE THREAD

**Issue by pravinthakare** [kalasjocke/authlogic-facebook-connect#12]
I'm really struggling to get the authlogic_facebook_connect plugin to behave.

Currently, the first attempt with Facebook Connect works fine, creating a new User and session with the correct uid. The problem is that any subsequent attempt to connect with a different Facebook user will always log me in as that first User. 
the Session always seems to persist and the plugin loads the User based on that initial uid.

Anyone have some advice on what I'm doing wrong? or tell me how can in invalidate facebook session from my log-out method

Many thanks

Pravin

**Comment by kjf** [comment]
I'm experiencing the exact same problem. Have you managed to find a solution?

**Comment by bitzesty** [comment]
facebooker issue, i fixed this by switching to mongrel - see devise_facebook_connect issues for full thread.

**Comment by ghost** [comment]
FYI, I think this is the thread blitzesty was talking about:
http://github.com/grimen/devise_facebook_connectable/issues/15

**Comment by yuvalkarmi** [comment]
had the same thing, you gotta call the FB.connect.logout function and then redirect.
I'm using jQuery, and this is how I did it:
http://pastie.org/1127192
