### ISSUE TITLE
Associate existing user with facebook account

### ISSUE THREAD

**Issue by dsmalko** [kalasjocke/authlogic-facebook-connect#16]
Is it possible?

**Comment by papayaah** [comment]
this plugin is highly undocumented. the documentation is overly simplified thinks that everyone here is an expert and expect to read between the lines.

**Comment by pcasa** [comment]
+1
Can create user, but creates user every time.  how? find_or_create_user_by(facebook_uid)

**Comment by mnelson** [comment]
this is hacky but it does the job: http://gist.github.com/600328

**Comment by trobrock** [comment]
I have a fork of this plugin that works with the new Graph API, the only thing it is lacking right now is connecting to an existing user, if anyone has some ideas on how this could be done and require the user to authenticate to the account they are connecting to let me know.

**Comment by trobrock** [comment]
My fork now supports the new JS API and can connect to existing users, take a look here: https://github.com/studybyte/authlogic_facebook_connect
