### ISSUE TITLE
authlogic_facebook_connect breaks authlogic-oauth

### ISSUE THREAD

**Issue by joelmahoney** [kalasjocke/authlogic-facebook-connect#17]
after installing the authlogic_facebook_connect plugin, the oauth login with Twitter method no longer works.  the error originates at authlogic_facebook_connect/lib/authlogic_facebook_connect/session.rb:132:in `authenticating_with_facebook_connect?'

here's the error:
NoMethodError in User sessionsController#create
You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.+

here's the stack trace:
/opt/local/lib/ruby/gems/1.8/gems/facebooker-1.0.67/lib/facebooker/rails/controller.rb:125:in `fb_cookie_prefix'
/opt/local/lib/ruby/gems/1.8/gems/facebooker-1.0.67/lib/facebooker/rails/controller.rb:129:in`fb_cookie_names'
/opt/local/lib/ruby/gems/1.8/gems/facebooker-1.0.67/lib/facebooker/rails/controller.rb:129:in `select'
/opt/local/lib/ruby/gems/1.8/gems/facebooker-1.0.67/lib/facebooker/rails/controller.rb:129:in`fb_cookie_names'
/opt/local/lib/ruby/gems/1.8/gems/facebooker-1.0.67/lib/facebooker/rails/controller.rb:135:in `secure_with_cookies!'
/opt/local/lib/ruby/gems/1.8/gems/facebooker-1.0.67/lib/facebooker/rails/controller.rb:30:in`create_facebook_session'
/opt/local/lib/ruby/gems/1.8/gems/facebooker-1.0.67/lib/facebooker/rails/controller.rb:44:in `set_facebook_session'
/opt/local/lib/ruby/gems/1.8/gems/authlogic-2.1.3/lib/authlogic/controller_adapters/abstract_adapter.rb:63:in`send'
/opt/local/lib/ruby/gems/1.8/gems/authlogic-2.1.3/lib/authlogic/controller_adapters/abstract_adapter.rb:63:in `method_missing'
path_to_my_app/vendor/plugins/authlogic_facebook_connect/lib/authlogic_facebook_connect/session.rb:132:in`authenticating_with_facebook_connect?'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:178:in `send'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:178:in`evaluate_method'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:195:in `should_run_callback?'
/opt/local/lib/ruby/gems/1.8/gems/authlogic-2.1.3/lib/authlogic/session/password.rb:127:in`all?'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:195:in `each'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:195:in`all?'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:195:in `should_run_callback?'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:166:in`call'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:93:in `run'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:92:in`each'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:92:in `send'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:92:in`run'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:276:in `run_callbacks'
/opt/local/lib/ruby/gems/1.8/gems/authlogic-2.1.3/lib/authlogic/session/callbacks.rb:72:in`validate'
/opt/local/lib/ruby/gems/1.8/gems/authlogic-2.1.3/lib/authlogic/session/validation.rb:64:in `valid?'
/opt/local/lib/ruby/gems/1.8/gems/authlogic-2.1.3/lib/authlogic/session/existence.rb:65:in`save'
/opt/local/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth/session.rb:46:in `save'
path_to_my_app/app/controllers/user_sessions_controller.rb:15:in`create'

any suggestions?

**Comment by agibralter** [comment]
I think I ran into something similar. My fork has a hook so that you can turn on/off facebook login: http://github.com/agibralter/authlogic_facebook_connect/commit/9758277409849f8282f096f55c22ba8cd17c149d

Here is an example of how I use it: http://gist.github.com/360833

**Comment by marcandre** [comment]
I believe it is because of a bad design decision of auth_logic itself.
See http://github.com/binarylogic/authlogic/issues#issue/58  (and vote it up or comment!)

**Comment by joelmahoney** [comment]
I switched to http://github.com/jbasdf/authlogic_facebook_connect and everything worked fine (note that you need an additional User field compared with the kalasjocke version: add_column :users, :facebook_session_key, :string)
