### ISSUE TITLE
self.attempted_record.save_with_validation(false) causes errors

### ISSUE THREAD

**Issue by techyak** [kalasjocke/authlogic-facebook-connect#2]
When I try to create a new session for a user that doesn't exist in the database it throws an error saying that the persistence_token can't be null.  Perhaps I don't fully understand what I'm supposed to do to fix that problem, but if I just change your code to: "self.attempted_record.save_with_validation(true)" or even "self.attempted_record.save" everything works just fine.  Did I just compromise something by making this change?  

By the way I'm using facebooker 1.0.44 and authlogic 2.1.1 and the latest version of your plugin (as of July 30th).

Thanks for creating this plugin by the way!

**Comment by kalasjocke** [comment]
I can't reproduce your error, please have a look at my forked authlogic_example application and see whats diffs [1]. It maybe be the validations in the database that causes the issue.

[1] http://github.com/kalasjocke/authlogic_example/tree/master

**Comment by techyak** [comment]
I just took a look and you're right.  I left in the validation from authlogic which says that the persistence_token can't be null.  This is probably just my lack of expertise, but because authlogic states that the persistence token is required I didn't feel that I could safely remove the validation.  Now that I've removed it the problem is solved.  Thanks for following up with me - and thanks again for creating the plugin.

**Comment by kalasjocke** [comment]
Ah great then! I should probably mention that you need to remove the standard validations if you want to create unvalid users what only uses facebook connect!

**Comment by sowenjub** [comment]
That would be helpful indeed :) I was just about to report the same issue!
Isn't there any side effects of not preventing the persistence token to be null ?
Thanks for this plugin.

**Comment by csanz** [comment]
Guys I ran into the same issue, how do I remove all validations? 

BTW, this is the error I get (same thing) http://gist.github.com/339599

**Comment by csanz** [comment]
nevermind I fixed it

**Comment by fullware** [comment]
Is this documented somewhere? I'm a little confused and not sure disabling all validations would be a good idea.
