### ISSUE TITLE
extended permissions

### ISSUE THREAD

**Issue by keone** [kalasjocke/authlogic-facebook-connect#22]
How does one request extended permissions?  Adding a :perms key to the hash 

<pre>
<%#= authlogic_facebook_login_button :text => 'Login with Facebook', :v => 2, :perms => "email,user_birthday" %>
</pre>

causes the FBML to render as

<pre>
&lt;form id='connect_to_facebook_form' method='post' action='/user_session'&gt;
<br>&lt;input type='hidden' name='authenticity_token' value='CODE HERE'/&gt;
<br>&lt;/form&gt;
<br>&lt;script type='text/javascript' charset='utf-8'&gt;
<br> function connect_to_facebook() {
<br>   $('connect_to_facebook_form').submit();
<br> }
<br>&lt;/script&gt;
<br>&lt;fb:login-button js=&quot;prototype&quot; onlogin=&quot;connect_to_facebook()&quot; perms=&quot;email,user_birthday&quot; v=&quot;2&quot;&gt;Login with Facebook&lt;/fb:login-button&gt;
</pre>

but clicking on the button serves up the vanilla no-extended-permissions popup, so the form submission is clearly not picking up the perms key-value pair off of the login-button.

What to do?

Thanks.

**Comment by fadhlirahim** [comment]
Hi, you have to define it at the init_fb_connect like so

<%= init_fb_connect "XFBML", {:app_settings => " { permsToRequestOnConnect : 'email' }"}  %>

**Comment by keone** [comment]
thanks, this is perfect.
