### ISSUE TITLE
Does not work with Facebooks new JS API

### ISSUE THREAD

**Issue by trobrock** [kalasjocke/authlogic-facebook-connect#27]
Is there any plan to change this plugin to use facebooker2 and the new JS API from facebook?

**Comment by kalasjocke** [comment]
Currently No. It may however be subject to change later on when I can free more time to develop this plugin. If you are interested to make this move i can add you as a developer.

**Comment by trobrock** [comment]
I forked the project to work on this, having some troubles in the session.rb mostly because I am having trouble following exactly what needs to be done for authlogic to be satisfied.

**Comment by kalasjocke** [comment]
Thats awesome. Yeah i know, session.rb could be a little hard at times. Good luck!

**Comment by trobrock** [comment]
Do you have any good references of what needs to happen in session.rb or have some time to walk me through what your copy does?

**Comment by kalasjocke** [comment]
Nope, i dont have any good reference for the session.rb. I think the best way to do it is just to play around with it and see what works and what dosn't.

**Comment by trobrock** [comment]
Ok well, I will try and keep everyone posted
