### ISSUE TITLE
Rails 3 compatible?

### ISSUE THREAD

**Issue by kimptoc** [kalasjocke/authlogic-facebook-connect#29]
Hi,

Is this plugin Rails 3 compatible?

I have tried using it in a sample app - https://github.com/kimptoc/Authlogic-Scratch/commits/authlogic_facebook_connect

But the authlogic_facebook_login_button tag is returning html encoded html - eg &lt; ... rather than < .

Thanks,
Chris

**Comment by melki** [comment]
Same problem

**Comment by kalasjocke** [comment]
@melki The last commit was 3 years ago and the project is currently unmaintained. If you would like to add Rails 3 support I'm all for it.
