### ISSUE TITLE
undefined method `rw_config' for UserSession:Class

### ISSUE THREAD

**Issue by scream3** [kalasjocke/authlogic-facebook-connect#3]
I get this error when try to login with Facebook connect.
Either problem in example rails app.

Here is application trace:

/home/scream3/Temp/authlogic_example/vendor/plugins/authlogic_facebook_connect/lib/authlogic_facebook_connect/session.rb:37:in `facebook_uid_field'

/home/scream3/Temp/authlogic_example/vendor/plugins/authlogic_facebook_connect/lib/authlogic_facebook_connect/session.rb:99:in `facebook_uid_field'

/home/scream3/Temp/authlogic_example/vendor/plugins/authlogic_facebook_connect/lib/authlogic_facebook_connect/session.rb:59:in `validate_by_facebook_connect'

/home/scream3/Temp/authlogic_example/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `send'

/home/scream3/Temp/authlogic_example/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'

/home/scream3/Temp/authlogic_example/vendor/rails/activesupport/lib/active_support/callbacks.rb:166:in `call'

/home/scream3/Temp/authlogic_example/vendor/rails/activesupport/lib/active_support/callbacks.rb:93:in `run'

/home/scream3/Temp/authlogic_example/vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in `each'

/home/scream3/Temp/authlogic_example/vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in `send'

/home/scream3/Temp/authlogic_example/vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in `run'

/home/scream3/Temp/authlogic_example/vendor/rails/activesupport/lib/active_support/callbacks.rb:276:in `run_callbacks'

/usr/lib/ruby/gems/1.8/gems/authlogic-2.0.11/lib/authlogic/session/callbacks.rb:71:in `validate'

/usr/lib/ruby/gems/1.8/gems/authlogic-2.0.11/lib/authlogic/session/validation.rb:58:in `valid?'

/usr/lib/ruby/gems/1.8/gems/authlogic-2.0.11/lib/authlogic/session/existence.rb:63:in `save'

/home/scream3/Temp/authlogic_example/app/controllers/user_sessions_controller.rb:11:in `create'

**Comment by kalasjocke** [comment]
It seams that you are not using the latest version of the Authlogic gem, please update!

**Comment by scream3** [comment]
yes, thanks. troubles was in my ruby installation.
