### ISSUE TITLE
Jquery support

### ISSUE THREAD

**Issue by m3m3nto** [kalasjocke/authlogic-facebook-connect#4]
Hi and thanks for your work!

I'm experimenting some issues using this plugin.
In my application i use JQuery and the jrails plugin.
Your helper.rb at line 13:

output += "   $('connect_to_facebook_form').submit();\n"

offers only the prototype selector.
So, we don't have support for JQuery while facebooker offers this feature.
You think that there will be in the future, or it is better a fork?

**Comment by grimen** [comment]
I successfully impemented Facebook Connect with jQuery based on this plugin. Actualyl works out of the box for Facebooker if you do _something_ like this:

http://pastie.org/635266

I had to do some tweaking of other stuff though, but not really jQuery-related as I remember.

**Comment by kalasjocke** [comment]
Hey, grimen, please send a pull request!

**Comment by m3m3nto** [comment]
Thanks grimen, 
i'll study your snippet, then i'll try port in erb.

**Comment by m3m3nto** [comment]
Hello all,
using grimen suggestions my application works fine.
Thanks!

**Comment by ippa** [comment]
Is jQuery support implemented yet?

**Comment by seboslaw** [comment]
I second that question

**Comment by kalasjocke** [comment]
It is now as a patch from Michał Szajbe!
