### ISSUE TITLE
Errors in testuites

### ISSUE THREAD

**Issue by m3m3nto** [kalasjocke/authlogic-facebook-connect#5]
Hello, and sorry for this new issue!
I've noticed that installing the plugin without any other implementation, many of my tests (units, functionals) return a NoMethodError.
In units for example:

NoMethodError: undefined method `set_facebook_session' for #ActionController::TestRequest:0xb4f53a70

I'm using rails 2.3.4, ruby 1.8.7 (Ubuntu 9.0.4) and i've installed the plugin into a fresh checkout of my trunk; before installing the plugin all my tests are ok.
Anyone got the same error?
Thanks!

**Comment by grimen** [comment]
Sounds like you haven't required Facebooker in your environment; should solve your problems.

**Comment by m3m3nto** [comment]
Hi grimen,
my enviroment.rb includes facebooker gem:

config.gem "facebooker", :version => '~> 1.0.50' 

My application works perfectly, 
but tests still return a NoMethodError.

**Comment by grimen** [comment]
Hmm, OK. Try to "force-incude" the Facebooker helpers where the error occurs. This is not related to this plugin, it's def related to Facebooker. I recommend filing an issue if you don' get anywhere: http://github.com/mmangino/facebooker

**Comment by shwoodard** [comment]
I have the exact same issue.

**Comment by ghost** [comment]
No - its actually caused by a callback that is assuming the Rails controller instead what actually in scope in a test (MockController) - see the follow gist for patch:

http://gist.github.com/221893

**Comment by m3m3nto** [comment]
Thanks endax,
testsuite are ok.

**Comment by tfwright** [comment]
This issue is closed, but it looks like the problem still exists in source...is no one using this plugin testing?
