### ISSUE TITLE
Placement of authlogic_facebook_login_button

### ISSUE THREAD

**Issue by marcandre** [kalasjocke/authlogic-facebook-connect#6]
If one places <%= authlogic_facebook_login_button %> inside the form_for, things will almost work but not quite.

If it's easy to do, it would be nice if it worked one way or another.

Otherwise it might be worth specifying more precisely where to put the authlogic_facebook_login_button in the instructions.

Thanks!

**Comment by kalasjocke** [comment]
Yeah, im working on better documentation and this will be taken care of, the problem is that it creates forms inside of forms!
