### ISSUE TITLE
tokens

### ISSUE THREAD

**Issue by sowenjub** [kalasjocke/authlogic-facebook-connect#7]
Hello,

I commented about the persistence token in an other issue yesterday but I've got just a little more material since then.
In my app right now I use 3 tokens : persistence, perishable and single_access. Following Authlogic example app (Ben's one), the three tokens should not be allowed NULL. I'd like to preserve that since I plan to have both facebook and non-facebook users.

perishable_token and single_access_token don't mess up facebook connect, and before_connect seems a good place to set them in case you have to (maybe you could add that to the readme if it is).
So my code looks like :
  def before_connect(facebook_session)
    self.single_access_token = Authlogic::Random.friendly_token
    self.perishable_token = Authlogic::Random.friendly_token
    self.first_name = facebook_session.user.first_name
    self.last_name = facebook_session.user.last_name
  end

Unfortunately, this doesn't work with the persistence_token.
It's really strange because if I add a persistence_token the same way I do for the two other tokens (friendly_token or hex_token), it gets impossible to login.
But, if I set the facebook_uid to an existing "regular" user (that has a persistence_token), he will be able to log in.
Also, if I manually edit the database entry and put whatever token, it will also.

So it looks like the random token generated during before_connect isn't acceptable, but I don't know why.

Do you have any clue regarding this behavior ?

Thanks

**Comment by kalasjocke** [comment]
Uh, i actually dont know as i dont use my plugin with regular users. My best guess is to take this directly with Ben as he knows about the tokens better than i do! 

Good luck!

**Comment by sowenjub** [comment]
Ok, thanks for your reply
