### ISSUE TITLE
Error trying to validate the session

### ISSUE THREAD

**Issue by paraseba** [kalasjocke/authlogic-facebook-connect#8]
Once the user is authenticated using the Connect button, I get this error any time authlogic tries to validate the session: 

undefined method `user' for #User:0x7f1b215fc5b0

in:

/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:260:in `method_missing'
/vendor/plugins/authlogic_facebook_connect/lib/authlogic_facebook_connect/session.rb:80:in`try'
/vendor/plugins/authlogic_facebook_connect/lib/authlogic_facebook_connect/session.rb:80:in `validate_by_facebook_connect'

I think the problem is with this line:
        self.attempted_record = facebook_user_class.find(:first, :conditions => { facebook_uid_field => facebook_session.user.uid }).try(:"#{klass}".to_s.underscore)

It looks strange,  it basically does  "User.find(...).user" so it fails.

**Comment by szajbus** [comment]
Check out the commit in my fork http://github.com/szajbus/authlogic_facebook_connect/commit/056be92153730bea60e7270b80d65d4a0ade1320

It seems to deal with the problem.

I already sent a pull request to kalasjocke, but he still has not merged it in.

**Comment by sjain** [comment]
This seems to be merged into master - this issue should be closed now.
