### ISSUE TITLE
Undefined method 'new_user'

### ISSUE THREAD

**Issue by sailing** [kalasjocke/authlogic-facebook-connect#9]
Using the most recent version, with the session_key field added by David Li. 

After a user authenticates with facebook (in the popup window), facebook redirects them to mysite.com/user_sessions, where this error is thrown:

<pre>
user_sessions#create (NameError) "undefined local variable or method `new_user' for #<UserSession: no credentials provided>"
</pre>

And here's the end of the backtrace: 

<pre>
/home/mysite/releases/20091202235230/vendor/plugins/authlogic_facebook_connect/lib/authlogic_facebook_connect/session.rb:102:in `validate_by_facebook_connect'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:178:in `send'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:178:in `evaluate_method'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:166:in `call'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:93:in `run'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:92:in `each'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:92:in `send'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:92:in `run'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/callbacks.rb:276:in `run_callbacks'
/home/rails/.gem/ruby/1.8/gems/authlogic-2.1.2/lib/authlogic/session/callbacks.rb:72:in `validate'
/home/rails/.gem/ruby/1.8/gems/authlogic-2.1.2/lib/authlogic/session/validation.rb:64:in `valid?'
/home/rails/.gem/ruby/1.8/gems/authlogic-2.1.2/lib/authlogic/session/existence.rb:65:in `save'
</pre>

I'm not sure what other information you need.

My callback url in facebook is mysite.com/users and the callback redirect is mysite.com/account.

Thanks in advance for your support and the plugin.

**Comment by kalasjocke** [comment]
This is now corrected with the latest patch from taweili!
